#Quick script for plotting variance measures of sky brightness for poster.
require(dplyr)
require(plyr)
require(ggplot2)
require(relaimpo)
require(matrixStats)
require(Hmisc)
require(corrplot)
require("PerformanceAnalytics")
require(ggmap)
require(maps)
require(mapview)
require(mapdata)
require(munsell)
require(leaflet)
require(devtools)
require(webshot)
require(stats)
require(segmented)
require(viridis)

wd <- "~/Desktop/Coastlight"
setwd(wd)

#Read in data generated by SQC batch analysis.
SQCData <- read.table("CoastlightSkyVarianceAllSites.csv", header=TRUE, sep=",",as.is=T,skip=0,fill=TRUE,check.names=FALSE, encoding = "UTF-8")
SQCData <- arrange(SQCData,`SQC File Name`)
#Rename verbose variables
colnames(SQCData)[which(names(SQCData) == "Scalar Illuminance")] <- "ScalarIlluminance"

#Calculate whole sky coefficient of variation in scalar illuminance
SkySectors <- (SQCData[grepl("D(.*?)R(.*?)Luminance", names(SQCData))])
SectorNames <- colnames(SkySectors)
SkySectors[SkySectors<0] <- 0
SkySectors$SDLuminance <- rowSds(as.matrix(SkySectors),na.rm=TRUE)
SkySectors$MeanLuminance <- rowMeans(SkySectors[SectorNames],na.rm=TRUE)
SkySectors$CoVLuminance <- SkySectors$SDLuminance/SkySectors$MeanLuminance
SkySectors$`SQC File Name` <- SQCData$`SQC File Name`
#Merge in these scalar illuminance statistics into the batch analyses data set.
SQCData <- left_join(SQCData,SkySectors[,c("SQC File Name","MeanLuminance","SDLuminance","CoVLuminance")],by=c("SQC File Name"))

#Read in 2012 VIIRS upwards radiance data per site.
VIIRS <- read.table("LPPointsUnder150.csv", header=TRUE, sep=",",as.is=T,skip=0,fill=TRUE,check.names=FALSE)
VIIRS[,'Latitude'] = round(VIIRS[,'Latitude'],5)
VIIRS[,'Longitude'] = round(VIIRS[,'Longitude'],5)
colnames(VIIRS)[which(names(VIIRS) == "Brightness (nW/Sr/cm^2)")] <- "VIIRSBrightness"

#Read in field data.
FieldData <- read.table("CoastlightFieldData.csv", header=TRUE, sep=",",as.is=T,skip=0,fill=TRUE,check.names=FALSE)
FieldData[,'Centroid latitude'] = round(FieldData[,'Centroid latitude'],5)
FieldData[,'Centroid longitude'] = round(FieldData[,'Centroid longitude'],5)
colnames(FieldData)[which(names(FieldData) == "SQM2015Atlas (mcd/m^2)")] <- "SQA"

#Merge in VIIRS data by pixel to field data.
FieldData <- left_join(FieldData,VIIRS[,c("Latitude","Longitude","VIIRSBrightness","OBJECTID")],by=c("Centroid latitude" = "Latitude","Centroid longitude" = "Longitude"))

#Create unique site ID.  Each site contains 5 locations.
colnames(FieldData)[which(names(FieldData) == "OBJECTID")] <- "UniqueID"
FieldData$UniqueID <- as.factor(as.character(FieldData$UniqueID))

#Keep batch analysis data for images with zero horizon.
SQCDataZeroHorizon <- SQCData[!grepl("Horizon",SQCData$'SQC File Name'),]
SQCDataZeroHorizon <- arrange(SQCDataZeroHorizon,`SQC File Name`)

#Keep batch analysis data for images with edited horizon.
SQCDataEditedHorizon <- SQCData[grepl("Horizon",SQCData$'SQC File Name'),]
SQCDataEditedHorizon <- arrange(SQCDataEditedHorizon,`SQC File Name`)

#Zero-horizon merged data set
FieldSQCMergeZH <- left_join(FieldData,SQCDataZeroHorizon,by=c("SQCSiteName"="Location"))
#Edited-horizon merged data set
FieldSQCMergeEH <- left_join(FieldData,SQCDataEditedHorizon,by=c("SQCSiteName"="Location"))
#Determine the fraction of horizon radiance to full sky radiance.
FieldSQCMergeZH$HorizonLuminance <- (FieldSQCMergeZH$ScalarIlluminance - FieldSQCMergeEH$ScalarIlluminance)
FieldSQCMergeEH$HorizonLuminance <- (FieldSQCMergeZH$ScalarIlluminance - FieldSQCMergeEH$ScalarIlluminance)

#Subset horizon-edited data for analysis of spatial variability of scalar illuminance.
SpatialEH <- FieldSQCMergeEH
SpatialEH <- SpatialEH[,c("UniqueID","ScalarIlluminance")]
SpatialEH <- arrange(SpatialEH,UniqueID)
#Determine the mean of scalar illuminance by UniqueID
tmp <- as.data.frame(aggregate(SpatialEH$ScalarIlluminance,by=list(SpatialEH$UniqueID),FUN=mean))
colnames(tmp) <- c("UniqueID","ScalarIlluminanceSiteMean")
SpatialEH <- merge(SpatialEH,tmp,by=c("UniqueID"))
#Determine the coefficient of variation of scalar illuminance by UniqueID
tmp <- as.data.frame(aggregate(SpatialEH$ScalarIlluminance,by=list(SpatialEH$UniqueID),FUN=function(ScalarIlluminance){sd(ScalarIlluminance)/mean(ScalarIlluminance)}))
colnames(tmp) <- c("UniqueID","ScalarIlluminanceSiteCoV")
SpatialEH <- merge(SpatialEH,tmp,by=c("UniqueID"))
#Merge into larger data set.
FieldSQCMergeEH <- left_join(FieldSQCMergeEH,SpatialEH,by=c("UniqueID"))

#Subset zero horizon data for analysis of spatial variability of scalar illuminance.
SpatialZH <- FieldSQCMergeZH
SpatialZH <- SpatialZH[,c("UniqueID","ScalarIlluminance")]
SpatialZH <- arrange(SpatialZH,UniqueID)
#Determine the mean of scalar illuminance by UniqueID
tmp <- as.data.frame(aggregate(SpatialZH$ScalarIlluminance,by=list(SpatialZH$UniqueID),FUN=mean))
colnames(tmp) <- c("UniqueID","ScalarIlluminanceSiteMean")
SpatialZH <- merge(SpatialZH,tmp,by=c("UniqueID"))
#Determine the coefficient of variation of scalar illuminance by UniqueID
tmp <- as.data.frame(aggregate(SpatialZH$ScalarIlluminance,by=list(SpatialZH$UniqueID),FUN=function(ScalarIlluminance){sd(ScalarIlluminance)/mean(ScalarIlluminance)}))
colnames(tmp) <- c("UniqueID","ScalarIlluminanceSiteCoV")
SpatialZH <- merge(SpatialZH,tmp,by=c("UniqueID"))
#Merge into larger data set.
FieldSQCMergeZH <- left_join(FieldSQCMergeZH,SpatialZH,by=c("UniqueID"))

#Full merged data set
FieldSQCMergeEH$TypeHorizon <- "EditedHorizon"
FieldSQCMergeZH$TypeHorizon <- "ZeroHorizon"
FieldSQCMergeEH$`ScalarIlluminance.y` <- NULL
FieldSQCMergeZH$`ScalarIlluminance.y` <- NULL
colnames(FieldSQCMergeEH)[which(names(FieldSQCMergeEH) == "ScalarIlluminance.x")] <- "ScalarIlluminance"
colnames(FieldSQCMergeZH)[which(names(FieldSQCMergeZH) == "ScalarIlluminance.x")] <- "ScalarIlluminance"
#Use the same %horizon values for both the full hemispheric and edited horizon images.
FieldSQCMergeZH$Horizon <- FieldSQCMergeEH$Horizon
FieldSQCMerge <- rbind(FieldSQCMergeZH,FieldSQCMergeEH)

#Compare models generated from full sky scalar illuminance, or the luminance from particular bands of the sky, using WAANSB and the input variable.
#Try a logrithmic model of scalar illuminance versus VIIRS for the full data set for the full hemispheric images.
LPLogModelZH <- lm(log10(ScalarIlluminance)~log10(VIIRSBrightness+1),data=FieldSQCMergeZH)
FieldSQCMergeZH$LogFit <- log10((FieldSQCMergeZH$VIIRSBrightness+1)*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$ScalarIlluminance),log10(FieldSQCMergeZHSubset$VIIRSBrightness+1))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(VIIRSBrightness+1),y=log10(ScalarIlluminance),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(VIIRS+1)"~log(nW/Sr/cm^2)))+ylab("Log(SI (mlx))")+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Try a logrithmic model of scalar illuminance versus VIIRS for the full data set for the full hemispheric images.
FieldSQCMergeZHSubset <- subset(FieldSQCMergeZH,Clouds==0)
LPLogModelZH <- lm(log10(ScalarIlluminance)~log10(VIIRSBrightness+1),data=FieldSQCMergeZHSubset)
FieldSQCMergeZHSubset$LogFit <- log10((FieldSQCMergeZHSubset$VIIRSBrightness+1)*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZHSubset,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$ScalarIlluminance),log10(FieldSQCMergeZHSubset$VIIRSBrightness+1))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(VIIRSBrightness+1),y=log10(ScalarIlluminance),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(VIIRS+1)"~log(nW/Sr/cm^2)))+ylab("Log(SI (mlx))")+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Compare models generated from full sky scalar illuminance, or the luminance from particular bands of the sky, using WAANSB and the input variable.

#Try a logrithmic model of scalar illuminance versus WAANSB for the full data set for the full hemispheric images.
LPLogModelZH <- lm(log10(ScalarIlluminance)~log10(SQA),data=FieldSQCMergeZH)
FieldSQCMergeZH$LogFit <- log10(FieldSQCMergeZH$SQA*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$ScalarIlluminance),log10(FieldSQCMergeZHSubset$SQA))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(SQA),y=log10(ScalarIlluminance),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab("Log(SI (mlx))\nFull hemisphere")+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))
#Plot residuals of scalar illuminance to log model versus color temperature
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=`CCT (Scalar)`,y=log10(ScalarIlluminance)-LogFit))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=ScalarIlluminance-LogFit))
LPPlotZH+xlab("CCT (K)")+ylab("(Observed - Modeled) SI\nlog(mlx)")
cor.test(FieldSQCMergeZHSubset$`CCT (Scalar)`,log10(FieldSQCMergeZHSubset$ScalarIlluminance)-FieldSQCMergeZHSubset$LogFit)

#Try a logrithmic model of scalar illuminance versus WAANSB for the data set with no cloud cover for the full hemispheric images.
FieldSQCMergeZHSubset <- subset(FieldSQCMergeZH,Clouds==0)
LPLogModelZH <- lm(log10(ScalarIlluminance)~log10(SQA),data=FieldSQCMergeZHSubset)
FieldSQCMergeZHSubset$LogFit <- log10(FieldSQCMergeZHSubset$SQA*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZHSubset,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$ScalarIlluminance),log10(FieldSQCMergeZHSubset$SQA))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(SQA),y=log10(ScalarIlluminance),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab("Log(SI (mlx))\nFull hemisphere")+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Plot fitted scalar illuminance (Using log model) versus log(WAANSB) for ring 1 (Top 30 degrees of the sky using full hemispheric images)
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("Ring 1Luminance","Ring 1CCT"))
LPLogModelZH <- lm(log10(`Ring 1Luminance`)~log10(SQA),data=FieldSQCMergeZHSubset)
FieldSQCMergeZHSubset$LogFit <- log10(FieldSQCMergeZHSubset$SQA*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZHSubset,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$SQA),log10(FieldSQCMergeZHSubset$`Ring 1Luminance`))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(SQA),y=log10(`Ring 1Luminance`),color=`Ring 1CCT`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab(expression(atop("Log(L) Top 30°",paste("Log(mcd/",m^{2},")"))))+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Plot fitted scalar illuminance (Using log model) versus log(WAANSB) for ring 1 (Top 30 degrees of the sky using images without cloud cover)
FieldSQCMergeZHSubset <- na.omit(subset(FieldSQCMergeZH,Clouds==0),cols=c("Ring 1Luminance","Ring 1CCT"))
LPLogModelZH <- lm(log10(`Ring 1Luminance`)~log10(SQA),data=FieldSQCMergeZHSubset)
FieldSQCMergeZHSubset$LogFit <- log10(FieldSQCMergeZHSubset$SQA*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZHSubset,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$SQA),log10(FieldSQCMergeZHSubset$`Ring 1Luminance`))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(SQA),y=log10(`Ring 1Luminance`),color=`Ring 1CCT`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab(expression(atop("Log(L) Top 30°",paste("Log(mcd/",m^{2},")"))))+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Plot fitted scalar illuminance (Using log model) versus log(WAANSB) for ring 7 (Bottom 10 degrees of the sky using full hemispheric images)
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("Ring 7Luminance","Ring 7CCT"))
LPLogModelZH <- lm(log10(`Ring 7Luminance`)~log10(SQA),data=FieldSQCMergeZHSubset)
FieldSQCMergeZHSubset$LogFit <- log10(FieldSQCMergeZHSubset$SQA*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZHSubset,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$SQA),log10(FieldSQCMergeZHSubset$`Ring 7Luminance`))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(SQA),y=log10(`Ring 7Luminance`),color=`Ring 7CCT`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab(expression(atop("Log(L) Bottom 10°",paste("Log(mcd/",m^{2},")"))))+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Plot fitted scalar illuminance (Using log model) versus log(WAANSB) for ring 7 (Bottom 10 degrees of the sky using images without cloud cover)
FieldSQCMergeZHSubset <- na.omit(subset(FieldSQCMergeZH,Clouds==0),cols=c("Ring 7Luminance","Ring 7CCT"))
LPLogModelZH <- lm(log10(`Ring 7Luminance`)~log10(SQA),data=FieldSQCMergeZHSubset)
FieldSQCMergeZHSubset$LogFit <- log10(FieldSQCMergeZHSubset$SQA*LPLogModelZH$coefficients[2])+LPLogModelZH$coefficients[1]
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZHSubset,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeZHSubset$SQA),log10(FieldSQCMergeZHSubset$`Ring 7Luminance`))
#Plot model
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(SQA),y=log10(`Ring 7Luminance`),color=`Ring 7CCT`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotZH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab(expression(atop("Log(L) Bottom 10°",paste("Log(mcd/",m^{2},")"))))+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Try a logrithmic model of scalar illuminance versus WAANSB for the full set of edited horizon images.
FieldSQCMergeEHSubset <- FieldSQCMergeEH
LPLogModelEH <- lm(log10(ScalarIlluminance)~log10(SQA),data=FieldSQCMergeEHSubset)
FieldSQCMergeEHSubset$LogFit <- log10(FieldSQCMergeEHSubset$SQA*LPLogModelZH$coefficients[2])+LPLogModelEH$coefficients[1]
FieldSQCMergeEHSubset <- na.omit(FieldSQCMergeEHSubset,cols=c("LogFit"))
cor.test(log10(FieldSQCMergeEHSubset$ScalarIlluminance),log10(FieldSQCMergeEHSubset$SQA))
#Plot model
LPPlotEH <- ggplot(FieldSQCMergeEHSubset, aes(x=log10(SQA),y=log10(ScalarIlluminance),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotEH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab("Log(SI (mlx))\nEdited horizon")+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

#Try a logrithmic model of scalar illuminance versus WAANSB for the data set with no cloud cover for the edited horizon images.
FieldSQCMergeEHSubset <- subset(FieldSQCMergeEH,Clouds==0)
LPLogModelEH <- lm(log10(ScalarIlluminance)~log10(SQA),data=FieldSQCMergeEHSubset)
FieldSQCMergeEHSubset$LogFit <- log10(FieldSQCMergeEHSubset$SQA*LPLogModelZH$coefficients[2])+LPLogModelEH$coefficients[1]
FieldSQCMergeEHSubset <- na.omit(FieldSQCMergeEHSubset,cols=c("LogFit"))
cor.test(FieldSQCMergeEHSubset$LogFit,FieldSQCMergeEHSubset$SQA)
#Plot model
LPPlotEH <- ggplot(FieldSQCMergeEHSubset, aes(x=log10(SQA),y=log10(ScalarIlluminance),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=LogFit))
LPPlotEH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab("Log(SI (mlx))\nEdited horizon")+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))

##Color temperature versus luminance for the top and bottom bands of the sky.

#Plot color temperature versus luminance for ring 1, the top 30 degrees of the sky.  Use full hemispheric images.
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("Ring 1Luminance","Ring 1CCT"))
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(`Ring 1Luminance`),y=`Ring 1CCT`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=`Ring 1CCT`))
LPPlotZH+xlab( bquote("Log(Ring 1 Luminance)"~log(mcd/m^2)))+ylab("Ring 1 CCT (K)")
cor.test(FieldSQCMergeZHSubset$`Ring 1CCT`,log10(FieldSQCMergeZHSubset$`Ring 1Luminance`))
mean(FieldSQCMergeZHSubset$`Ring 1CCT`)
sd(FieldSQCMergeZHSubset$`Ring 1CCT`)
mean(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 1Luminance`>=0),c("Ring 1Luminance")])
sd(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 1Luminance`>=0),c("Ring 1Luminance")])

#Plot color temperature versus luminance for ring 7, the bottom 10 degrees of the sky.  Use full hemispheric images.
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("Ring 7Luminance","Ring 7CCT"))
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=log10(`Ring 7Luminance`),y=`Ring 7CCT`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=`Ring 7CCT`))
LPPlotZH+xlab( bquote("Log(Ring 7 Luminance)"~(mcd/m^2)))+ylab("Ring 7 CCT (K)")
cor.test(FieldSQCMergeZHSubset$`Ring 7CCT`,log10(FieldSQCMergeZHSubset$`Ring 7Luminance`))
mean(FieldSQCMergeZHSubset$`Ring 7CCT`)
sd(FieldSQCMergeZHSubset$`Ring 7CCT`)
mean(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 7Luminance`>=0),c("Ring 7Luminance")])
sd(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 7Luminance`>=0),c("Ring 7Luminance")])

#Boxplot of luminance values for the top and bottom rings of the sky.
tmp <- as.data.frame(FieldSQCMergeZH$`Ring 1Luminance`)
colnames(tmp) <- c("Luminance")
tmp$Ring <- "Top 30°"
tmp2 <- as.data.frame(FieldSQCMergeZH$`Ring 7Luminance`)
colnames(tmp2) <- c("Luminance")
tmp2$Ring <- "Bottom 10°"
tmp <- rbind(tmp,tmp2)
tmp <- na.omit(tmp)
tmp <- tmp[!duplicated(tmp),]
tmp <- subset(tmp,Luminance>=0)
tmp$Ring <- as.factor(tmp$Ring)
LPBoxPlot <- ggplot(tmp,aes(x=Ring,y=Luminance))+geom_boxplot()
LPBoxPlot <- LPBoxPlot + scale_x_discrete(name = "Section of sky") + scale_y_continuous(name = bquote("L"~(mcd/m^2)))
LPBoxPlot <- LPBoxPlot  + theme(axis.text.x=element_text(colour="black", size = 25), axis.text.y=element_text(colour="black", size = 25),text=element_text(size = 25))
LPBoxPlot
mean(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 1Luminance`>=0),c("Ring 1Luminance")])
mean(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 7Luminance`>=0),c("Ring 7Luminance")])
wilcox.test(na.omit(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 1Luminance`>=0),c("Ring 1Luminance")]),na.omit(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 7Luminance`>=0),c("Ring 7Luminance")]),alternative="two.sided")

#Boxplot of color temperature values for the top and bottom rings of the sky.
tmp <- as.data.frame(FieldSQCMergeZH$`Ring 1CCT`)
colnames(tmp) <- c("CCT")
tmp$Ring <- "Top 30°"
tmp2 <- as.data.frame(FieldSQCMergeZH$`Ring 7CCT`)
colnames(tmp2) <- c("CCT")
tmp2$Ring <- "Bottom 10°"
tmp <- rbind(tmp,tmp2)
tmp <- na.omit(tmp)
tmp <- tmp[!duplicated(tmp),]
tmp$Ring <- as.factor(tmp$Ring)
LPBoxPlot <- ggplot(tmp,aes(x=Ring,y=CCT))+geom_boxplot()
LPBoxPlot <- LPBoxPlot + scale_x_discrete(name = "Section of sky") + scale_y_continuous(name = "CCT (K)")
LPBoxPlot <- LPBoxPlot  + theme(axis.text.x=element_text(colour="black", size = 25), axis.text.y=element_text(colour="black", size = 25),text=element_text(size = 25))
LPBoxPlot
mean(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 1Luminance`>=0),c("Ring 1CCT")])
mean(FieldSQCMergeZH[which(FieldSQCMergeZH$`Ring 7Luminance`>=0),c("Ring 7CCT")])
wilcox.test(na.omit(FieldSQCMergeZH$`Ring 1CCT`),na.omit(FieldSQCMergeZH$`Ring 7CCT`),alternative="two.sided")

#Plot coefficient of variation on scalar illuminance within VIIRS pixels.
LPPlotZH <- ggplot(FieldSQCMergeZH, aes(x=log10(VIIRSBrightness+1),y=ScalarIlluminanceSiteCoV))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=CoVLuminance))
LPPlotZH+xlab(bquote("Log(VIIRS+1)"~log(nW/Sr/cm^2)))+ylab("CoV on SI within sites")
cor.test(log10(FieldSQCMergeZH$VIIRSBrightness+1),FieldSQCMergeZH$ScalarIlluminanceSiteCoV)
#
LPPlotZH <- ggplot(FieldSQCMergeZH, aes(x=log10(SQA),y=ScalarIlluminanceSiteCoV))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=CoVLuminance))
LPPlotZH+xlab(bquote("Log(WAANSB)"~log(mcd/m^2)))+ylab("CoV on SI within sites")
cor.test(log10(FieldSQCMergeZH$SQA),FieldSQCMergeZH$ScalarIlluminanceSiteCoV)

#Plot coefficient of variation on luminance within images.
LPPlotZH <- ggplot(FieldSQCMergeZH, aes(x=Clouds,y=CoVLuminance))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=CoVLuminance))
LPPlotZH+xlab("% Clouds")+ylab("CoV on Luminance")
cor.test(FieldSQCMergeZH$Clouds,FieldSQCMergeZH$CoVLuminance)
#
LPPlotZH <- ggplot(FieldSQCMergeZH, aes(x=Horizon,y=CoVLuminance))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=CoVLuminance))
LPPlotZH+xlab("% Horizon")+ylab("CoV on Luminance")
cor.test(FieldSQCMergeZH$Horizon,FieldSQCMergeZH$CoVLuminance)

#Plot mean SQM readings against luminance in different regions of the sky.
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("Ring 1Luminance"))
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=SQMMean,y=log10(`Ring 1Luminance`),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=log10(`Ring 1Luminance`)))
LPPlotZH+xlab("SQM Mean (mag)")+ylab(expression(atop("Log(L) Top 30°",paste("Log(mcd/",m^{2},")"))))+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))
LPLogModelZH <- lm(log10(`Ring 1Luminance`)~SQMMean,data=FieldSQCMergeZHSubset)
cor.test(FieldSQCMergeZHSubset$SQMMean,log10(FieldSQCMergeZHSubset$`Ring 1Luminance`))
#
FieldSQCMergeZHSubset <- na.omit(FieldSQCMergeZH,cols=c("Ring 7Luminance"))
LPPlotZH <- ggplot(FieldSQCMergeZHSubset, aes(x=SQMMean,y=log10(`Ring 7Luminance`),color=`CCT (Scalar)`))+geom_point()+theme(text = element_text(size=25))+geom_smooth(method=glm, aes(fill=log10(`Ring 7Luminance`)))
LPPlotZH+xlab("SQM Mean (mag)")+ylab(expression(atop("Log(L) Bottom 10°",paste("Log(mcd/",m^{2},")"))))+scale_color_gradientn("CCT (K)",colours = rev(plasma(10)),limits=c(1500,5000))
LPLogModelZH <- lm(log10(`Ring 7Luminance`)~SQMMean,data=FieldSQCMergeZHSubset)
cor.test(FieldSQCMergeZHSubset$SQMMean,log10(FieldSQCMergeZHSubset$`Ring 7Luminance`))

#To map various measures of coastal light pollution.
MapCoordinates <- FieldSQCMergeZH
colnames(MapCoordinates)[which(names(MapCoordinates) == "Latitude")] <- "SQCLatitude"
colnames(MapCoordinates)[which(names(MapCoordinates) == "Longitude")] <- "SQCLongitude"
colnames(MapCoordinates)[which(names(MapCoordinates) == "Adjusted latitude")] <- "latitude"
colnames(MapCoordinates)[which(names(MapCoordinates) == "Adjusted longitude")] <- "longitude"
MapCoordinates <- MapCoordinates[!is.na(MapCoordinates$latitude) & !is.na(MapCoordinates$longitude),]
CalMap = leaflet(MapCoordinates) %>% 
  addTiles()
ColorScale <- colorNumeric(palette=plasma(10),domain=log10(FieldSQCMergeZH$SQA))
CalMap %>% addCircleMarkers(color = ~ColorScale(log10(SQA)), fill = TRUE,radius=2,fillOpacity = 0.1) %>% 
  addProviderTiles(providers$Esri.WorldTopoMap) %>%
  leaflet::addLegend(position="topright", pal=ColorScale,values=~log10(SQA),opacity=1,title="Log(WAANSB)<br>Log(mcd/m<sup>2</sup>)")
