#Quick script for plotting variance measures of sky brightness for poster.
require(dplyr)
require(plyr)
require(ggplot2)
require(relaimpo)
require(matrixStats)
require(Hmisc)
require(corrplot)
require("PerformanceAnalytics")

wd <- "~/Desktop/Coastlight"
setwd(wd)

#Read in data generated by SQC batch analysis.
SQCData <- read.table("CoastlightEHSkyVariance94Sites.csv", header=TRUE, sep=",",as.is=T,skip=0,fill=TRUE,check.names=FALSE)
SQCData <- arrange(SQCData,`SQC File Name`)

#Calculate whole sky coefficient of variation in scalar illuminance
SkySectors <- (SQCData[grepl("D(.*?)R(.*?)Luminance", names(SQCData))])
SectorNames <- colnames(SkySectors)
SkySectors<-transform(as.matrix(SkySectors),SDLuminance=rowSds(as.matrix(SkySectors),na.rm=TRUE)) 
SkySectors$MeanLuminance <- rowMeans(SkySectors[SectorNames],na.rm=TRUE)
SkySectors$CoVLuminance <- SkySectors$SDLuminance/SkySectors$MeanLuminance
SkySectors$`SQC File Name` <- SQCData$`SQC File Name`
#Merge in these scalar illuminance statistics into the batch analyses data set.
SQCData <- left_join(SQCData,SkySectors[,c("SQC File Name","MeanLuminance","SDLuminance","CoVLuminance")],by=c("SQC File Name"))

#Read in 2012 VIIRS upwards radiance data per site.
VIIRS <- read.table("LPPointsUnder150.csv", header=TRUE, sep=",",as.is=T,skip=0,fill=TRUE,check.names=FALSE)
VIIRS[,'Latitude'] = round(VIIRS[,'Latitude'],5)
VIIRS[,'Longitude'] = round(VIIRS[,'Longitude'],5)

#Read in field data.
FieldData <- read.table("CoastlightFieldData.csv", header=TRUE, sep=",",as.is=T,skip=0,fill=TRUE,check.names=FALSE)
FieldData[,'Centroid latitude'] = round(FieldData[,'Centroid latitude'],5)
FieldData[,'Centroid longitude'] = round(FieldData[,'Centroid longitude'],5)

#Merge in VIIRS data by pixel to field data.
FieldData <- left_join(FieldData,VIIRS[,c("Latitude","Longitude","Brightness (nW/Sr/cm^2)")],by=c("Centroid latitude" = "Latitude","Centroid longitude" = "Longitude"))
#write.table(FieldData,"CoastligthFieldData.tsv",quote=FALSE,sep="\t",row.names = FALSE)

#Keep batch analysis data for images with zero horizon.
SQCDataZeroHorizon <- SQCData[!grepl("Horizon",SQCData$'SQC File Name'),]
SQCDataZeroHorizon <- arrange(SQCDataZeroHorizon,`SQC File Name`)

#Keep batch analysis data for images with edited horizon.
SQCDataEditedHorizon <- SQCData[grepl("Horizon",SQCData$'SQC File Name'),]
SQCDataEditedHorizon <- arrange(SQCDataEditedHorizon,`SQC File Name`)

#Zero-horizon merged data set
FieldSQCMergeZH <- left_join(FieldData,SQCDataZeroHorizon,by=c("SQCSiteName"="Location"))
#Edited-horizon merged data set
FieldSQCMergeEH <- left_join(FieldData,SQCDataEditedHorizon,by=c("SQCSiteName"="Location"))
#Determine the fraction of horizon radiance to full sky radiance.
FieldSQCMergeZH$HorizonLuminanceFraction <- (FieldSQCMergeZH$`Scalar Illuminance` - FieldSQCMergeEH$`Scalar Illuminance`) / FieldSQCMergeZH$`Scalar Illuminance`
FieldSQCMergeEH$HorizonLuminanceFraction <- (FieldSQCMergeZH$`Scalar Illuminance` - FieldSQCMergeEH$`Scalar Illuminance`) / FieldSQCMergeZH$`Scalar Illuminance`
#Full merged data set
FieldSQCMerge <- rbind(FieldSQCMergeZH,FieldSQCMergeEH)
#write.table(FieldSQCMerge,"CoastlightMerged94Sites.tsv",quote=FALSE,sep="\t",row.names = FALSE)

#Plot data for zero-horizon images
LPPlotZH <- ggplot(FieldSQCMergeZH, aes(x=`Brightness (nW/Sr/cm^2)`,y=log10(`Scalar Illuminance`),color=Clouds))+geom_point()+geom_smooth(method=glm, aes(fill=`Scalar Illuminance`))
LPPlotZH+xlab("VIIRS Upwards Radiance (nW/Sr/cm^2)")+ylab("Log(Scalar Illuminance (mlx)")+ggtitle("Log of Scalar Illuminance (Field data) vs. VIIRS Upwards Radiance (nW/Sr/cm^2)\nZero Horizon (94 Sites)")+scale_color_gradientn("% Cloud cover",colours = rainbow(5))
#
SQMPlotZH <- ggplot(FieldSQCMergeZH, aes(x=`Brightness (nW/Sr/cm^2)`,y=SQMMean,color=Clouds))+geom_point()+geom_smooth(method=glm, aes(fill=SQMMean))
SQMPlotZH+xlab("VIIRS Upwards Radiance (nW/Sr/cm^2)")+ylab("Mean SQM (mag, Field data)")+ggtitle("Mean SQM (mag, Field data) vs. VIIRS Upwards Radiance (nW/Sr/cm^2)\nZero Horizon (94 Sites)")+scale_color_gradientn("% Cloud cover",colours = rainbow(5))

#Plot data for horizon-edited images
LPPlotEH <- ggplot(FieldSQCMergeEH, aes(x=`Brightness (nW/Sr/cm^2)`,y=log10(`Scalar Illuminance`),color=Clouds))+geom_point()+geom_smooth(method=glm, aes(fill=`Scalar Illuminance`))
LPPlotEH+xlab("VIIRS Upwards Radiance (nW/Sr/cm^2)")+ylab("Log(Scalar Illuminance (mlx))")+ggtitle("Log of Scalar Illuminance (Field data) vs. SQM Atlas (Satellite data)\nEdited Horizon (94 Sites)")+scale_color_gradientn("% Cloud cover",colours = rainbow(5))
#
SQMPlotEH <- ggplot(FieldSQCMergeEH, aes(x=`Brightness (nW/Sr/cm^2)`,y=SQMMean,color=Clouds))+geom_point()+geom_smooth(method=glm, aes(fill=SQMMean))
SQMPlotEH+xlab("VIIRS Upwards Radiance (nW/Sr/cm^2)")+ylab("Mean SQM (mag, Field data)")+ggtitle("Mean SQM (mag, Field data) vs. VIIRS Upwards Radiance (nW/Sr/cm^2)\nZero Horizon (94 Sites)")+scale_color_gradientn("% Cloud cover",colours = rainbow(5))

#Fit a model to predict the log of the scalar illuminance from field data for horizon-edited images.
LPModelEH <- lm(log10(`Scalar Illuminance`)~Horizon+Clouds+`SQM2015Atlas (mcd/m^2)`+`Brightness (nW/Sr/cm^2)`,data=FieldSQCMergeEH)
summary(LPModelEH)
printCoefmat(coef(summary(step(LPModelEH))))
calc.relimp(LPModelEH)

#Fit a model to predict the log of the scalar illuminance from field data for zero-horizon images.
LPModelZH <- lm(log10(`Scalar Illuminance`)~Horizon+Clouds+`SQM2015Atlas (mcd/m^2)`+`Brightness (nW/Sr/cm^2)`,data=FieldSQCMergeZH)
summary(LPModelZH)
printCoefmat(coef(summary(step(LPModelZH))))
calc.relimp(LPModelZH)

##Correlations of variance light pollution variables.
#Each significance level is associated to a symbol : p-values(0, 0.001, 0.01, 0.05, 0.1, 1) <=> symbols(“***”, “**”, “*”, “.”, " “)
chart.Correlation(FieldSQCMergeZH[,c("Scalar Illuminance","SDLuminance","SQM2015Atlas (mcd/m^2)","Brightness (nW/Sr/cm^2)","Clouds","Horizon","HorizonLuminanceFraction")], histogram=FALSE, method="spearman")
chart.Correlation(FieldSQCMergeEH[,c("Scalar Illuminance","SDLuminance","SQM2015Atlas (mcd/m^2)","Brightness (nW/Sr/cm^2)","Clouds","Horizon","HorizonLuminanceFraction")], histogram=FALSE, method="spearman")

#Subset horizon-edited data for analysis of spatial variability of scalar illuminance.
SpatialEH <- FieldSQCMergeEH
#UniqueID is the unique combination of 2015 sky atlas brightness with the GPS coordinates
#of the centroid of the 2015 sky atlas pixel
#SQCData$UniqueID <- paste(SQCData$Latitude,",",SQCData$Longitude,",",SQCData$`SQM2015Atlas (mcd/m^2)`,sep="")

SpatialEH <- SpatialEH[,c("UniqueID","Horizon","Scalar Illuminance","SQMMean")]
SpatialEH <- arrange(SpatialEH,UniqueID)

#Determine the mean of scalar illuminance by UniqueID
tmp <- as.data.frame(aggregate(SpatialEH$`Scalar Illuminance`,by=list(SpatialEH$UniqueID),FUN=mean))
colnames(tmp) <- c("UniqueID","ScalarIlluminanceMean")
SpatialEH <- merge(SpatialEH,tmp,by=c("UniqueID"))
#Determine the coefficient of variation of scalar illuminance by UniqueID
tmp <- as.data.frame(aggregate(SpatialEH$`Scalar Illuminance`,by=list(SpatialEH$UniqueID),FUN=function(ScalarIlluminance){sd(ScalarIlluminance)/mean(ScalarIlluminance)}))
colnames(tmp) <- c("UniqueID","ScalarIlluminanceCoV")
SpatialEH <- merge(SpatialEH,tmp,by=c("UniqueID"))
